// Keep this registry aligned with src/hames/event_types.py. EventSource has no
// wildcard listener, so the browser must name each typed SSE event it accepts.
export const durableEventTypes = `
flow.started
flow.created
flow.updated
session.opened
session.closed
session.forked
session.settings.changed
session.agent.changed
session.mode.changed
session.title.changed
session.pinned.changed
user.message
queue.enqueued
queue.updated
queue.removed
queue.promoted
queue.prioritized
queue.paused
queue.resumed
plan.proposed
plan.note.queued
plan.note.applied
plan.execution.requested
plan.approved
plan.execution.started
plan.execution.resumed
plan.execution.attention
plan.execution.completed
plan.execution.failed
tasks.replaced
task.added
task.updated
task.removed
user.correction
assistant.message
assistant.reasoning
context.compiled
context.compaction.started
context.compaction.completed
context.compaction.failed
context.compaction.cancelled
goal.created
goal.step.started
goal.progressed
goal.yielded
goal.resumed
goal.paused
goal.achieved
goal.blocked
goal.cancelled
model.requested
model.provider_state
model.response.started
model.usage
model.tool_call
model.response.completed
model.response.failed
model.response.preempted
run.started
run.continuation.requested
run.completed
run.failed
run.cancelled
tool.requested
tool.started
tool.completed
tool.failed
tool.rejected
policy.requested
policy.decided
approval.requested
approval.resolved
question.requested
question.answered
trust.granted
trust.revoked
runtime.error
runtime.notice
terminal.started
terminal.completed
terminal.failed
terminal.stopped
delegation.requested
delegation.task_card
delegation.completed
delegation.failed
delegation.followup.completed
delegation.followup.failed
delegation.stopping
memory.proposed
memory.accepted
memory.rejected
memory.superseded
memory.retracted
memory.deleted
memory.promoted
memory.job.queued
memory.job.started
memory.job.completed
memory.job.failed
memory.job.paused
dream.started
dream.paused
dream.completed
dream.failed
memory.retrieved
memory.episode.projected
memory.capture.requested
memory.promotion.requested
skill.authoring.requested
skill.workflow.observed
skill.evolution.triggered
skill.job.queued
skill.job.started
skill.job.completed
skill.job.failed
skill.job.paused
skill.drafted
skill.validated
skill.evaluated
skill.rejected
skill.activated
skill.superseded
skill.quarantined
skill.rolled_back
skill.catalogued
skill.loaded
skill.executed
skill.outcome.recorded
skill.control.requested
skill.staled
skill.archived
skill.deleted
skill.restored
skill.pinned
skill.unpinned
scar.recorded
scar.opened
scar.dismissed
scar.deleted
scar.edited
scar.repair_proposed
scar.guarded
scar.triggered
scar.guard.succeeded
scar.healed
scar.regressed
scar.repair.proposed
scar.repair.promoted
scar.repair.rejected
scar.repair.evaluated
correction.verdict
context.rule.proposed
context.rule.activated
context.rule.retired
policy.rule.proposed
policy.rule.activated
policy.rule.retired
plugin.installed
plugin.enabled
plugin.disabled
plugin.removed
plugin.worker.started
plugin.worker.stopped
plugin.worker.failed
plugin.capability.registered
plugin.broker.requested
plugin.broker.completed
plugin.proposal.created
`.trim().split(/\s+/);

export const transientEventTypes = [
  "response.snapshot",
  "response.reasoning_delta",
  "response.text_delta",
  "response.tool_call_delta",
  "event",
] as const;

export const sessionEventTypes = [...durableEventTypes, ...transientEventTypes];
