import { cleanup, fireEvent, render, screen } from "@solidjs/testing-library";
import { createSignal } from "solid-js";
import { afterEach, expect, it, vi } from "vitest";
import type { HamesEvent, Session } from "../api/types";
import { SessionChat } from "./SessionChat";
const fixture = vi.hoisted(() => ({ events: () => [] as HamesEvent[] }));
vi.mock("./sessionStream", () => ({ createSessionStream: () => ({ events: () => fixture.events(), state: () => "live", liveOutput: () => undefined }) }));
vi.mock("../agents/AgentDirectory", () => ({ useAgentDirectory: () => ({ ensureLoaded: async () => {}, agents: () => [] }) }));
vi.mock("../shell/workspace", () => ({ useWorkspace: () => ({}) }));
vi.mock("../api/client", () => ({ getDelegatedSessions: async () => [{ id: "child", parent_session_id: "parent", fork_event_id: "delegation", lineage_kind: "delegation", agent_id: "builder" }] }));
vi.mock("./components/TaskPanel", () => ({ TaskPanel: () => null, createTaskCardState: () => ({ tasks: () => [], refresh: () => {} }) }));
vi.mock("./components/ChatFrame", () => ({ ChatFrame: (props: { children: unknown }) => props.children }));
vi.mock("./components/ChatSessionBar", () => ({ ChatSessionBar: (props: { agentStatus?: string; onAgentsToggle: () => void }) => <>{props.agentStatus && <button onClick={props.onAgentsToggle}>Agents</button>}</> }));
vi.mock("./components/ConversationViewport", () => ({ ConversationViewport: () => null }));
vi.mock("./components/MessageComposer", () => ({ MessageComposer: () => null }));
vi.mock("./events/EventsView", () => ({ EventsView: () => null }));
vi.mock("../shell/WorkspaceSwitcher", () => ({ WorkspaceSwitcher: () => null }));
vi.mock("../delegation/AgentTranscriptDrawer", () => ({ AgentTranscriptDrawer: (props: { onToggleMaximize: () => void }) => <div>Current worker transcript<button onClick={props.onToggleMaximize}>Maximize</button></div> }));
afterEach(cleanup);
const event = (id: string, type: string, run_id: string, payload = {}): HamesEvent => ({ id, type, run_id, session_id: "parent", sequence: 1, payload } as HamesEvent);
it("does not close on session polling, and retains delegated agents across ordinary turns", async () => {
  const [events, setEvents] = createSignal([event("start", "run.started", "old"), event("delegation", "delegation.requested", "old", { target_agent_id: "builder" })]);
  fixture.events = events;
  const [session, setSession] = createSignal({ id: "parent", agent_id: "default", working_directory: "/project", title: "Chat" } as Session);
  const { container } = render(() => <SessionChat session={session()} onSessionChanged={() => {}} onSessionUpdated={() => {}} onSessionOpened={() => {}} />);
  fireEvent.click(await screen.findByRole("button", { name: "Agents" }));
  expect(container.querySelector(".agent-drawer-shell")).toHaveClass("open");
  fireEvent.click(screen.getByRole("button", { name: "Maximize" }));
  expect(container.querySelector(".agent-chat-layout")).toHaveClass("drawer-maximized");
  setSession({ ...session(), title: "Updated by polling" });
  expect(container.querySelector(".agent-chat-layout")).toHaveClass("drawer-maximized");
  expect(container.querySelector(".agent-drawer-shell")).toHaveClass("open");
  setEvents([...events(), event("done", "delegation.completed", "old", { target_agent_id: "builder", child_session_id: "child" })]);
  expect(container.querySelector(".agent-drawer-shell")).toHaveClass("open");
  setEvents([...events(), event("finish", "run.completed", "old")]);
  expect(screen.getByRole("button", { name: "Agents" })).toBeInTheDocument();
  setEvents([...events(), event("followup", "run.started", "followup")]);
  expect(container.querySelector(".agent-drawer-shell")).toHaveClass("open");
  expect(screen.getByRole("button", { name: "Agents" })).toBeInTheDocument();
  setEvents([...events(), event("next", "run.started", "new")]);
  expect(container.querySelector(".agent-drawer-shell")).toHaveClass("open");
  expect(screen.getByRole("button", { name: "Agents" })).toBeInTheDocument();
});
